# Generated by Django 4.1.3 on 2022-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
